# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: longship.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0elongship.proto\x12\x04Ship\"\xae\x01\n\x11PackageListResult\x12K\n\x13package_list_result\x18\x01 \x03(\x0b\x32..Ship.PackageListResult.PackageListResultEntry\x1aL\n\x16PackageListResultEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.Ship.PackageItems:\x02\x38\x01\"\x1a\n\x0cPackageItems\x12\n\n\x02id\x18\x01 \x03(\t\"0\n\x10LongShipResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x10\n\x08response\x18\x02 \x01(\t2V\n\x08LongShip\x12J\n\x15\x43reateLongShipFromVRP\x12\x17.Ship.PackageListResult\x1a\x16.Ship.LongShipResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'longship_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PACKAGELISTRESULT_PACKAGELISTRESULTENTRY']._options = None
  _globals['_PACKAGELISTRESULT_PACKAGELISTRESULTENTRY']._serialized_options = b'8\001'
  _globals['_PACKAGELISTRESULT']._serialized_start=25
  _globals['_PACKAGELISTRESULT']._serialized_end=199
  _globals['_PACKAGELISTRESULT_PACKAGELISTRESULTENTRY']._serialized_start=123
  _globals['_PACKAGELISTRESULT_PACKAGELISTRESULTENTRY']._serialized_end=199
  _globals['_PACKAGEITEMS']._serialized_start=201
  _globals['_PACKAGEITEMS']._serialized_end=227
  _globals['_LONGSHIPRESPONSE']._serialized_start=229
  _globals['_LONGSHIPRESPONSE']._serialized_end=277
  _globals['_LONGSHIP']._serialized_start=279
  _globals['_LONGSHIP']._serialized_end=365
# @@protoc_insertion_point(module_scope)
