# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import longship_pb2 as longship__pb2


class LongShipStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateLongShipFromVRP = channel.unary_unary(
                '/Ship.LongShip/CreateLongShipFromVRP',
                request_serializer=longship__pb2.PackageListResult.SerializeToString,
                response_deserializer=longship__pb2.LongShipResponse.FromString,
                )


class LongShipServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateLongShipFromVRP(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LongShipServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateLongShipFromVRP': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateLongShipFromVRP,
                    request_deserializer=longship__pb2.PackageListResult.FromString,
                    response_serializer=longship__pb2.LongShipResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Ship.LongShip', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LongShip(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateLongShipFromVRP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Ship.LongShip/CreateLongShipFromVRP',
            longship__pb2.PackageListResult.SerializeToString,
            longship__pb2.LongShipResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
